"""Aggregate the per-file surfaces into the ``data/corpus.xml`` summary.

The aggregate answers two questions the per-file sidecars cannot:

  * which corpus files exercise a given feature (to find a test file), and
  * how heavily a feature is used in the wild vs. only in synthetic coverage
    (to prioritize what ``mx::api`` should support).

Elements are ordered by wild-file usage, descending, so the most common
real-world features come first. Wild file lists are capped (the count attribute
is always exact); synthetic files are listed in full since there are few.
"""

from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass, field
from pathlib import Path

from .discover import CorpusFile, discover
from .extract import extract_file

# How many wild example files to list per element/attribute. The `count`
# attribute is exact regardless; this only bounds the listed sample.
WILD_FILE_CAP = 12

_SYNTH_VERSION_RE = re.compile(r"\.(\d+\.\d+)\.(?:xml|musicxml)$")


def _esc(text: str) -> str:
    # File paths are the only free-form text here; element/attribute names are
    # NCNames and cannot carry XML-special characters.
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def synthetic_version(rel: str) -> str:
    """The MusicXML version a synthetic file is named for (``note.3.1.xml`` ->
    ``3.1``), or "" if the name does not encode one."""
    m = _SYNTH_VERSION_RE.search(rel.rsplit("/", 1)[-1])
    return m.group(1) if m else ""


@dataclass
class _Usage:
    """Accumulator for one element or attribute across the corpus."""

    wild: list[str] = field(default_factory=list)  # data-relative paths
    synthetic: list[str] = field(default_factory=list)

    def add(self, rel: str, is_synthetic: bool) -> None:
        (self.synthetic if is_synthetic else self.wild).append(rel)


@dataclass
class _Element:
    files: _Usage = field(default_factory=_Usage)
    attrs: dict[str, _Usage] = field(default_factory=lambda: defaultdict(_Usage))


def _aggregate(files: list[CorpusFile]) -> dict[str, _Element]:
    elements: dict[str, _Element] = defaultdict(_Element)
    for cf in files:
        ff = extract_file(cf.path, cf.rel)
        for name, attrs in ff.elements.items():
            el = elements[name]
            el.files.add(cf.rel, cf.synthetic)
            for attr in attrs:
                el.attrs[attr].add(cf.rel, cf.synthetic)
    return elements


def _min_version(rels: list[str]) -> str:
    versions = sorted(v for v in (synthetic_version(r) for r in rels) if v)
    return versions[0] if versions else ""


def _file_elements_xml(usage: _Usage, indent: str) -> list[str]:
    lines: list[str] = []
    wild_sorted = sorted(usage.wild)
    lines.append(f'{indent}<wild-files count="{len(usage.wild)}">')
    for rel in wild_sorted[:WILD_FILE_CAP]:
        lines.append(f"{indent}  <file>{_esc(rel)}</file>")
    if len(usage.wild) > WILD_FILE_CAP:
        lines.append(f"{indent}  <!-- {len(usage.wild) - WILD_FILE_CAP} more -->")
    lines.append(f"{indent}</wild-files>")
    syn = _min_version(usage.synthetic)
    attr = f' min-version="{syn}"' if syn else ""
    lines.append(f'{indent}<synthetic-files count="{len(usage.synthetic)}"{attr}>')
    for rel in sorted(usage.synthetic):
        v = synthetic_version(rel)
        va = f' version="{v}"' if v else ""
        lines.append(f"{indent}  <file{va}>{_esc(rel)}</file>")
    lines.append(f"{indent}</synthetic-files>")
    return lines


def render(files: list[CorpusFile], elements: dict[str, _Element]) -> str:
    total = len(files)
    n_wild = sum(1 for f in files if not f.synthetic)
    n_synth = total - n_wild
    n_el = len(elements)
    n_el_wild = sum(1 for e in elements.values() if e.files.wild)
    n_el_synth_only = n_el - n_el_wild

    # Most-used-in-the-wild first; ties broken by name.
    order = sorted(elements, key=lambda n: (-len(elements[n].files.wild), n))

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        "<!-- Generated by `python3 -m audit corpus`. Aggregate MusicXML feature",
        "     usage across the data/ corpus. Elements are ordered by wild-file",
        "     usage (descending). Do not edit by hand; regenerate with the tool. -->",
        "<corpus-features>",
        "  <summary>",
        f'    <files total="{total}" wild="{n_wild}" synthetic="{n_synth}"/>',
        f'    <elements total="{n_el}" used-in-wild="{n_el_wild}" '
        f'synthetic-only="{n_el_synth_only}"/>',
        "  </summary>",
        "  <elements>",
    ]
    for name in order:
        el = elements[name]
        w, s = len(el.files.wild), len(el.files.synthetic)
        minv = _min_version(el.files.synthetic)
        minv_attr = f' min-synthetic-version="{minv}"' if minv else ""
        lines.append(
            f'    <element name="{name}" total-files="{w + s}" '
            f'wild-files="{w}" synthetic-files="{s}"{minv_attr}>'
        )
        if el.attrs:
            lines.append("      <attributes>")
            attr_order = sorted(
                el.attrs, key=lambda a: (-len(el.attrs[a].wild), a)
            )
            for a in attr_order:
                au = el.attrs[a]
                lines.append(
                    f'        <attribute name="{a}" '
                    f'wild-files="{len(au.wild)}" synthetic-files="{len(au.synthetic)}"/>'
                )
            lines.append("      </attributes>")
        lines.extend(_file_elements_xml(el.files, "      "))
        lines.append("    </element>")
    lines.append("  </elements>")
    lines.append("</corpus-features>")
    lines.append("")
    return "\n".join(lines)


def build(data_root: Path) -> str:
    files = discover(data_root)
    elements = _aggregate(files)
    return render(files, elements)
